#include "FlightTrajectorySystem.hpp"

// Constructor implementation
FlightTrajectorySystem::FlightTrajectorySystem() {
    // This is where you could initialize member variables if you had any.
    // For this wrapper, all state is in the C code, so this can be empty.
}

// Initialization implementation
void FlightTrajectorySystem::initialize() {
    // Call the initialize functions for both generated C modules.
    // This ensures their internal states are set to their default values.
    altitude_smoothening_initialize();
    altitude_smoothening_p_initialize();
}

// Original model execution implementation
uint16_t FlightTrajectorySystem::runOriginalTrajectory(uint8_t currentTime, uint8_t totalTime, uint8_t startAltitude, uint8_t targetAltitude) {
    // 1. SET INPUTS:
    //    Assign the input values to the global input structure (`ExtU...`)
    //    that was generated by Simulink for the original model.
    altitude_smoothening_U.currenttime = currentTime;
    altitude_smoothening_U.totaltime = totalTime;
    altitude_smoothening_U.startaltitude = startAltitude;
    altitude_smoothening_U.targetaltitude = targetAltitude;

    // 2. EXECUTE STEP:
    //    Call the model's step function to run its calculations for one time step.
    altitude_smoothening_step();

    // 3. RETURN OUTPUT:
    //    Retrieve the result from the global output structure (`ExtY...`) and return it.
    return altitude_smoothening_Y.desiredaltitude;
}

// Modified model execution implementation
uint16_t FlightTrajectorySystem::runModifiedTrajectory(uint8_t currentTime, uint8_t totalTime, uint8_t startAltitude, uint8_t targetAltitude) {
    // 1. SET INPUTS:
    //    Assign the input values to the global input structure for the modified model.
    altitude_smoothening_p_U.currenttime = currentTime;
    altitude_smoothening_p_U.totaltime = totalTime;
    altitude_smoothening_p_U.startaltitude = startAltitude;
    altitude_smoothening_p_U.targetaltitude = targetAltitude;

    // 2. EXECUTE STEP:
    //    Call the modified model's step function.
    altitude_smoothening_p_step();

    // 3. RETURN OUTPUT:
    //    Retrieve the result from the modified model's global output structure and return it.
    return altitude_smoothening_p_Y.desiredaltitude;
}